# Generated by Django 6.1 on 2026-08-18 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_user__model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developers', to=settings.AUTH_USER_MODEL),
        ),
    ]
